name: Main build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build on main
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnet_version: 9.0.x