name: Main build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build on main
    uses: jrb306/reusable-workflows/.github/workflows/build-and-test.yml@main
    with:
      dotnet_version: 9.0.x