name: PR Verify

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  pr-verify:
    name: PR Verify
    uses: jrb306/reusable-workflows/.github/workflows/build-and-test.yml@main
    with:
      dotnet_version: 9.0.x